USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DEA.SD;

CREATE OR REPLACE TABLE PERMANENT_TABLE (
ID INT,
NAME STRING
);
ALTER TABLE PERMANENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 90;

CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_TABLE(
ID INT,
NAME STRING
);
ALTER TABLE TRANSIENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 2;

CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_TABLE(
ID INT,
NAME STRING
);
ALTER TABLE TEMPORARY_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 2;

SHOW TABLES; 


