USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DEA.SD;

CREATE OR REPLACE TABLE EMPLOYEES(
ID INTEGER,
NAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY FLOAT
);

INSERT INTO EMPLOYEES (ID, NAME, DEPARTMENT, SALARY)
VALUES (1, 'LAHARI GOBBURI', 'IT', 80000.00),
        (2, 'SOUMYA GADDAM', 'IT', 73000.00),
        (3, 'MALLIKA TANGEDA', 'SALES', 75000.00),
        (4, 'SPANDANA DIRSALA', 'MARKETING', 85000.00);

SELECT * FROM EMPLOYEES;

CREATE OR REPLACE VIEW IT_EMPLOYEES AS 
SELECT ID, NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT';

SELECT * FROM IT_EMPLOYEES;

CREATE OR REPLACE SECURE VIEW HR_EMPLOYEES AS 
SELECT ID, NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'HR';

SELECT * FROM HR_EMPLOYEES;


CREATE OR REPLACE VIEW EMPLOYEE_SALARIES AS 
SELECT DEPARTMENT,
SUM(SALARY) AS TITAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT * FROM EMPLOYEE_SALARIES;

CREATE OR REPLACE MATERIALIZED VIEW MATERIALIZED_EMPLOYEE_SALARIES AS 
SELECT DEPARTMENT,
SUM(SALARY) AS TITAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT * FROM MATERIALIZED_EMPLOYEE_SALARIES;

