USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DEA.SD;

CREATE OR REPLACE TABLE USER(
ID INTEGER,
NAME VARCHAR(50),
LOCATION VARCHAR(50),
EMAIL VARCHAR(50)
);

CREATE OR REPLACE STORAGE INTEGRATION S3_LOAD
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::470957633639:role/dea-snow-userrole'
STORAGE_ALLOWED_LOCATIONS = ('s3://dea-snow-user/');

DESC INTEGRATION S3_LOAD;

CREATE OR REPLACE STAGE S3_STAGE
STORAGE_INTEGRATION = S3_LOAD
URL = 's3://dea-snow-user/'
FILE_FORMAT = CSV_FORMAT

LIST @S3_STAGE;

COPY INTO USER
FROM @S3_STAGE
FILE_FORMAT = CSV_FORMAT

SELECT * FROM USER;
