PC_DBT_DB.SILVERUSE SCHEMA SCD2_DB.BRONZE;

CREATE STORAGE INTEGRATION snowflake_storage_s3
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::470957633639:role/sdsnowflakerole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://sdbucket-training-123/raw_data/');

    DESC Integration snowflake_storage_s3;

CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = true;

CREATE STAGE s3_test_stage
  STORAGE_INTEGRATION = snowflake_storage_s3
  URL = 's3://sdbucket-training-123/raw_data/'
  FILE_FORMAT = MY_CSV_FORMAT;

  ls @s3_test_stage;

CREATE OR REPLACE TABLE 
    SCD2_DB.BRONZE.WORK_PRODUCT_COPY
(
PRODUCT_ID VARCHAR(255) NOT NULL COLLATE 'en-ci'
,PRODUCT_NAME VARCHAR(255) NOT NULL COLLATE 'en-ci'
,CATEGORY VARCHAR(255) COLLATE 'en-ci'
,SELLING_PRICE VARCHAR(50) COLLATE 'en-ci'
,MODEL_NUMBER VARCHAR(50) COLLATE 'en-ci'
,ABOUT_PRODUCT VARCHAR(5000) COLLATE 'en-ci'
,PRODUCT_SPECIFICATION VARCHAR(5000) COLLATE 'en-ci'
,TECHNICAL_DETAILS VARCHAR(50000) COLLATE 'en-ci'
,SHIPPING_WEIGHT VARCHAR(30) COLLATE 'en-ci'
,PRODUCT_DIMENSIONS VARCHAR(100) COLLATE 'en-ci'
,INSERT_DTS TIMESTAMP_NTZ(6) NOT NULL
,UPDATE_DTS TIMESTAMP_NTZ(6) NOT NULL
,SOURCE_FILE_NAME VARCHAR(255) NOT NULL
,SOURCE_FILE_ROW_NUMBER VARCHAR(255) NOT NULL);

select * from PC_DBT_DB.GOLD.PRODUCT_VIEW
WHERE PRODUCT_ID = '4c69b61db1fc16e7013b43fc926e502d';