USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DEA.SD;

CREATE OR REPLACE TABLE EVENT(
EVENT VARIANT
);

CREATE OR REPLACE STORAGE INTEGRATION SNOWPIPE_LOAD
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::470957633639:role/dea-snowpipe-user'
STORAGE_ALLOWED_LOCATIONS = ('s3://dea-snow-user/SNOWPIPEEVENT/');

DESC INTEGRATION SNOWPIPE_LOAD;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = 'JSON';

CREATE OR REPLACE STAGE SNOWPIPE_STAGE
STORAGE_INTEGRATION = S3_LOAD
URL = 's3://dea-snow-user/SNOWPIPEEVENT/'
FILE_FORMAT = JSON_FORMAT

LIST @SNOWPIPE_STAGE;

CREATE OR REPLACE PIPE S3_PIPE
AUTO_INGEST = TRUE AS
COPY INTO EVENT 
FROM @SNOWPIPE_STAGE
FILE_FORMAT = (FORMAT_NAME = JSON_FORMAT);

SELECT SYSTEM$PIPE_STATUS('S3_PIPE');
SHOW PIPES;

SELECT * FROM EVENT;







