USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DEA.SD;

CREATE OR REPLACE TABLE customer(
ID INTEGER,
NAME VARCHAR(50),
AGE INTEGER,
STATE VARCHAR(50)
);
-- TABLE STAGE
LIST @%customer;
-- USER STAGE
LIST @~;
-- INTERNAL NAMED STAGE
CREATE OR REPLACE STAGE CUSTOMER_STAGE;

LIST @CUSTOMER_STAGE;

copy into customer
from @CUSTOMER_STAGE
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

select * from customer;

tRUNCATE TABLE customer;

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1;

COPY INTO customer
from @CUSTOMER_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);
SHOW FILE FORMATS;

select * from customer;


