USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DEA.SD;

CREATE OR REPLACE TABLE TRACK(
ID INT,
NAME VARCHAR(50),
JOIN_DATE DATE
);

INSERT INTO TRACK(ID, NAME, JOIN_DATE)
VALUES (1,'SUSH', '2015-09-19'),
        (2,'SAI','2025-10-18');

SELECT * FROM TRACK;


CREATE OR REPLACE TABLE TARGET(
ID INT,
NAME VARCHAR(50),
JOIN_DATE DATE,
CREATED_DAY VARCHAR,
CREATED_MONTH VARCHAR,
CREATED_YEAR VARCHAR
);

INSERT INTO TARGET
SELECT A.ID, A.NAME, A.JOIN_DATE,
DAY(A.JOIN_DATE) AS CREATED_DAY,
MONTH(A.JOIN_DATE) AS CREATED_MONTH,
YEAR(A.JOIN_DATE) AS CREATED_YEAR
FROM TRACK A
LEFT JOIN TARGET B
ON A.ID=B.ID
WHERE B.ID IS NULL;

SELECT * FROM TARGET;

INSERT INTO TRACK(ID, NAME, JOIN_DATE)
VALUES (3,'sid', '2035-09-10');

SELECT * FROM TRACK;
SELECT * FROM TARGET;

-- AFTER RUNNING INSERT INTO TARGET QUERY ABOVE MANUALLY
SELECT * FROM TRACK;
SELECT * FROM TARGET;

CREATE OR REPLACE TABLE TRACK2(
ID INT,
NAME VARCHAR(50),
JOIN_DATE DATE
);

INSERT INTO TRACK2(ID, NAME, JOIN_DATE)
VALUES (1,'SUSH', '2015-09-19'),
        (2,'SAI','2025-10-18');

SELECT * FROM TRACK2;

CREATE OR REPLACE TABLE TARGET2(
ID INT,
NAME VARCHAR(50),
JOIN_DATE DATE,
CREATED_DAY VARCHAR,
CREATED_MONTH VARCHAR,
CREATED_YEAR VARCHAR
);

CREATE OR REPLACE TASK MY_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO TARGET2
SELECT A.ID, A.NAME, A.JOIN_DATE,
DAY(A.JOIN_DATE) AS CREATED_DAY,
MONTH(A.JOIN_DATE) AS CREATED_MONTH,
YEAR(A.JOIN_DATE) AS CREATED_YEAR
FROM TRACK2 A
LEFT JOIN TARGET B
ON A.ID=B.ID
WHERE B.ID IS NULL;

SHOW TASKS;

ALTER TASK MY_TASK RESUME;
SHOW TASKS;
ALTER TASK MY_TASK SUSPEND;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(TASK_NAME => 'MY_TASK'));

INSERT INTO TRACK2(ID, NAME, JOIN_DATE)
VALUES (3, 'sid', '2035-09-10');

SELECT * FROM TRACK2;
SELECT * FROM TARGET2;
