USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DEA.SD;

CREATE OR REPLACE TABLE TEST (
ID INT,
NAME VARCHAR
);

INSERT INTO TEST VALUES
(1, 'SUSH'),
(2, 'SAI');

DELETE FROM TEST WHERE ID = 2;
SELECT * FROM TEST;

-- RETRIEVING FROM 2 MINUTES BACK
SELECT * FROM TEST AT(OFFSET => -60*2);

SHOW TABLES;

SELECT * FROM TEST AT(TIMESTAMP => '2025-09-21 13:50:10.515 -0700'::TIMESTAMP_TZ);

SELECT * FROM TEST BEFORE(STATEMENT => '01bf34e2-0000-339d-0000-0060158badb5');

CREATE OR REPLACE TABLE TEST_CLONE AS 
SELECT * FROM TEST BEFORE(STATEMENT => '01bf34e2-0000-339d-0000-0060158badb5');

TRUNCATE TABLE TEST;

INSERT INTO TEST (ID, NAME)
SELECT * FROM TEST_CLONE;

SELECT * FROM TEST;

DROP TABLE TEST_CLONE;
DROP TABLE TEST;
-- CAN RETRIEVE BACK TABLE, SCHEMA, DATABASE DROPPED 
UNDROP TABLE TEST;

CREATE OR REPLACE DATABASE TEST_DEA CLONE DEA;

DROP DATABASE TEST_DEA;





